import { ROLES } from "./roles";

export const PERMISSIONS = {
  /* ───────────── ROUTES ───────────── */

  VIEW_HOME: [ROLES.USER, ROLES.ADMIN],
  VIEW_LOGIN: [ROLES.USER, ROLES.ADMIN],

  VIEW_PRODUCTS: [ROLES.USER, ROLES.ADMIN],
  VIEW_PRODUCT_DETAILS: [ROLES.USER, ROLES.ADMIN],

  VIEW_CART: [ROLES.USER],
  CHECKOUT: [ROLES.USER],

  VIEW_ORDERS: [ROLES.USER],
  VIEW_ORDER_DETAILS: [ROLES.USER],

  PAYMENT: [ROLES.USER],

  /* ───────────── ADMIN ROUTES ───────────── */

  VIEW_ADMIN_DASHBOARD: [ROLES.ADMIN],
  VIEW_ADMIN_KYC_REVIEW: [ROLES.ADMIN],
  VIEW_ADMIN_KYC_QUEUE: [ROLES.ADMIN],
  VIEW_ADMIN_LOGS: [ROLES.ADMIN],

  VIEW_ADMIN_PRODUCTS: [ROLES.ADMIN],
  CREATE_PRODUCT: [ROLES.ADMIN],
  UPDATE_PRODUCT: [ROLES.ADMIN],
  DELETE_PRODUCT: [ROLES.ADMIN],
  VIEW_PRODUCT: [ROLES.ADMIN],

  VIEW_ADMIN_USERS: [ROLES.ADMIN],
  VIEW_USER_DETAILS: [ROLES.ADMIN],

  VIEW_ADMIN_ORDERS: [ROLES.ADMIN],
  VIEW_ADMIN_ORDER_DETAILS: [ROLES.ADMIN],
  UPDATE_ORDER_STATUS: [ROLES.ADMIN],
  REFUND_ORDER: [ROLES.ADMIN],

  VIEW_ADMIN_PAYMENTS: [ROLES.ADMIN],
  VIEW_ADMIN_INVOICES: [ROLES.ADMIN],
};
